#!/usr/bin/env python3
"""
Package plugin translations as JAR file for Confluence.
Creates JAR with atlassian-plugin.xml and properties file.
"""

import sys
import os
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
from datetime import datetime

# Load environment variables
try:
    from dotenv import load_dotenv
    env_path = Path(__file__).parent.parent / '.env'
    load_dotenv(env_path)
except ImportError:
    pass

try:
    from locale_utils import get_target_locale, get_locale_info
except ImportError:
    def get_target_locale():
        return os.getenv('TARGET_LANGUAGE', 'ru_RU').strip()
    def get_locale_info(locale=None):
        if locale is None:
            locale = get_target_locale()
        parts = locale.split('_')
        lang = parts[0].lower() if parts else 'ru'
        country = parts[1].upper() if len(parts) > 1 else parts[0].upper() if parts else 'RU'
        names = {'ru': 'Russian', 'de': 'German', 'fr': 'French', 'es': 'Spanish', 'it': 'Italian',
                 'pt': 'Portuguese', 'ja': 'Japanese', 'ko': 'Korean', 'zh': 'Chinese', 'pl': 'Polish'}
        lang_name = names.get(lang, lang.title())
        countries = {'RU': 'Russia', 'DE': 'Germany', 'FR': 'France', 'ES': 'Spain', 'IT': 'Italy',
                     'BR': 'Brazil', 'JP': 'Japan', 'KR': 'Korea', 'CN': 'China', 'TW': 'Taiwan', 'PL': 'Poland'}
        country_name = countries.get(country, country)
        return {'name': f'{lang_name} ({country_name})', 'language': lang, 'country': country}


def create_plugin_xml(group_name: str, version: str = "1.0.0", 
                     properties_path: str = None,
                     generator_name: str = "AstraTeam",
                     locale: str = None) -> str:
    """
    Create atlassian-plugin.xml content.
    
    For ALL plugins, uses a consistent pattern:
    - Key: net.seibertmedia.confluence.plugin.i18n-editor.{group-name}
           Last part changes based on group name
    - Location: ALWAYS net/seibertmedia/confluence/language/i18n/i18n (fixed)
    - Vendor: ALWAYS "AstraTeam" with GitHub URL (fixed, never changed)
    - Only name/description change to use generator_name and group name
    
    Args:
        group_name: Group name (e.g., 'linchpin-suite' or 'requirements-yogi')
                   Used to construct the key: net.seibertmedia.confluence.plugin.i18n-editor.{group_name}
        version: Plugin version
        properties_path: Path to properties file within JAR (defaults to fixed location)
        generator_name: Generator name (only affects name and description tags)
    
    Returns:
        XML content as string
    """
    # CRITICAL: Key is constructed as: net.seibertmedia.confluence.plugin.i18n-editor.{group-name}
    # Last part changes based on the group name
    i18n_plugin_key = f"net.seibertmedia.confluence.plugin.i18n-editor.{group_name}"
    
    # Location is ALWAYS this fixed value for ALL plugins
    if not properties_path:
        properties_path = "net/seibertmedia/confluence/language/i18n/i18n"
    
    # Extract display name from group name for name/description
    # Convert group name to title case: linchpin-suite -> Linchpin Suite
    display_name = group_name.replace('-', ' ').replace('_', ' ').title()
    
    # Create element with EXACT plugin key (no modifications) - only name/description change
    xml = ET.Element('atlassian-plugin', key=i18n_plugin_key, 
                    name=f"Language pack for {display_name} (generated by {generator_name})")
    xml.set('plugins-version', '2')
    
    # Plugin info
    plugin_info = ET.SubElement(xml, 'plugin-info')
    desc = ET.SubElement(plugin_info, 'description')
    desc.text = f"Language pack for {display_name} generated by {generator_name}"
    ver = ET.SubElement(plugin_info, 'version')
    ver.text = version
    # Vendor is ALWAYS AstraTeam with GitHub URL - never changes
    vendor = ET.SubElement(plugin_info, 'vendor', name="AstraTeam", url="https://github.com/astrateam-net/confluence-localization-toolkit")
    # Add read-only-access-mode-compatible parameter
    param = ET.SubElement(plugin_info, 'param', name="read-only-access-mode-compatible")
    param.text = "true"
    
    # Language - get from locale (default: ru_RU)
    if locale is None:
        locale = get_target_locale()
    locale_info = get_locale_info(locale)
    lang = ET.SubElement(xml, 'language', key=locale, name=locale_info['name'], 
                        language=locale_info['language'], country=locale_info['country'])
    
    # Resource - location must match the properties path structure
    resource = ET.SubElement(xml, 'resource', name="i18n-0", type="i18n", location=properties_path)
    
    # Convert to string with proper formatting
    ET.indent(xml, space=" ")
    xml_str = ET.tostring(xml, encoding='unicode')
    
    # Add XML declaration
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + xml_str


def package_jar(properties_file: str, group_name: str, output_jar: str,
                version: str = "1.0.0", properties_path: str = None,
                generator_name: str = "AstraTeam"):
    """
    Package properties file as JAR for Confluence plugin.
    
    Args:
        properties_file: Path to properties file
        plugin_key: Plugin key
        output_jar: Output JAR file path
        version: Plugin version
        properties_path: Path to properties file within JAR
    """
    props_path = Path(properties_file)
    if not props_path.exists():
        raise FileNotFoundError(f"Properties file not found: {properties_file}")
    
    # Create group-specific folder in output/ based on plugin key or properties file location
    output_path = Path(output_jar)
    
    # If output_jar doesn't include a directory path, try to determine group from properties file
    if not output_path.is_absolute() and (output_path.parent == Path('.') or str(output_path.parent) == ''):
        # Extract group from properties file path if it's in output/{group}/
        props_dir = Path(properties_file).parent
        if 'output' in str(props_dir) and len(props_dir.parts) > 1:
            # Extract group name from path like output/requirements-yogi/
            extracted_group = props_dir.parts[-1] if props_dir.parts[-1] != 'output' else props_dir.parts[-2] if len(props_dir.parts) > 2 else group_name
            # Use provided group_name, or extracted if not provided
            actual_group_name = group_name if group_name and group_name != 'default' else extracted_group
            output_dir = Path('output') / actual_group_name
            output_dir.mkdir(parents=True, exist_ok=True)
            # Use filename from output_jar or generate one
            if output_path.name:
                output_path = output_dir / output_path.name
            else:
                # Generate JAR name from group name
                output_path = output_dir / f"{actual_group_name}-i18n-pack-{version}.jar"
        else:
            # Use provided group_name
            output_dir = Path('output') / group_name
            output_dir.mkdir(parents=True, exist_ok=True)
            if output_path.name:
                output_path = output_dir / output_path.name
            else:
                output_path = output_dir / f"{group_name}-i18n-pack-{version}.jar"
    else:
        # Directory specified, ensure it exists
        output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Properties path is ALWAYS the fixed location for ALL plugins
    if not properties_path:
        properties_path = "net/seibertmedia/confluence/language/i18n/i18n"
    
    # Create JAR file (JAR is just a ZIP file)
    with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as jar:
        # Get locale for XML
        locale = get_target_locale()
        # Add atlassian-plugin.xml to root - pass group_name to construct key
        plugin_xml = create_plugin_xml(group_name, version, properties_path,
                                      generator_name=generator_name, locale=locale)
        jar.writestr('atlassian-plugin.xml', plugin_xml.encode('utf-8'))
        
        # Get locale for properties filename
        locale = get_target_locale()
        # Add properties file to the specified path
        jar_path = f"{properties_path}_{locale}.properties"
        jar.write(props_path, jar_path)
        
        # Also add as i18n_ru_RU.properties if path suggests it
        if jar_path.endswith('/i18n_ru_RU.properties'):
            # Already correct
            pass
        elif jar_path.endswith('/i18n/i18n_ru_RU.properties'):
            # Also add as i18n_ru_RU.properties in same directory
            alt_path = jar_path.replace('/i18n/i18n_ru_RU.properties', '/i18n/i18n_ru_RU.properties')
            # Actually same, so just keep original
            pass
    
    # Construct the plugin key from group name for display
    plugin_key = f"net.seibertmedia.confluence.plugin.i18n-editor.{group_name}"
    
    print(f"✓ Created JAR file: {output_path}")
    print(f"  Plugin key: {plugin_key}")
    print(f"  Version: {version}")
    print(f"  Properties file: {jar_path}")
    print(f"  File size: {output_path.stat().st_size / 1024:.1f} KB")


def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description='Package plugin translations as JAR file',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Package properties file as JAR
  python3 src/package_jar.py --properties output/i18n_ru_RU.properties \
    --plugin net.seibertmedia.confluence.linchpin-suite \
    --output output/linchpin-suite-i18n-pack-1.0.0.jar
  
  # Specify custom properties path in JAR
  python3 src/package_jar.py --properties output/comala_ru_RU.properties \
    --plugin com.comalatech.workflows \
    --output output/comala-i18n-pack-1.0.0.jar \
    --properties-path com/comalatech/workflows/language/i18n/i18n
        """
    )
    
    parser.add_argument('--properties', required=True,
                       help='Properties file path')
    parser.add_argument('--group', required=True,
                       help='Group name (e.g., linchpin-suite or requirements-yogi). Key will be: net.seibertmedia.confluence.plugin.i18n-editor.{group}')
    parser.add_argument('--output', required=True,
                       help='Output JAR file path')
    parser.add_argument('--version', default='1.0.0',
                       help='Plugin version (default: 1.0.0)')
    parser.add_argument('--properties-path',
                       help='Path to properties file within JAR (auto-detected if not specified)')
    # Vendor is ALWAYS AstraTeam - not configurable
    parser.add_argument('--generator-name', default='AstraTeam',
                       help='Generator name for plugin metadata (default: AstraTeam)')
    
    args = parser.parse_args()
    
    try:
        package_jar(
            args.properties,
            args.group,
            args.output,
            args.version,
            args.properties_path,
            generator_name=args.generator_name
        )
    except Exception as e:
        print(f"\nError: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()

